.PHONY: all clean
all: msg
	+make -f Makefile.dec_prepbufr

clean: msg
	rm -f *.o *.mod dec_prepbufr

msg:
	@echo ""
	@echo "============================================================"
	@echo " dec_prepbufr"
	@echo "============================================================"
