#!/usr/bin/env python
import argparse
import subprocess as sp
import os,sys, shutil
import datetime as dt
import tempfile

rootDir=os.getenv('CFS_LETKF_ROOT')
chgres_bin = rootDir+'/util/scripts/global_chgres.sh'


## Get the command line arguments
parser = argparse.ArgumentParser(
#    formatter_class = argparse.ArgumentDefaultsHelpFormatter,
    usage="chgres_cfsr --start YYYYMMDDHH [--end YYMMDDHH] [options]",
    description=(
      "converts a downloaded CFSR dataset into a different resolution")
)

g = parser.add_argument_group('required arguments')
g.add_argument('--start', required=True, help=(
    'start date of data to convert, format is "YYYYMMDDHH"'))
g.add_argument('--end', help=(
    'end date of data to convert, format is "YYYYMMDDHH", '
    ' if no start date is given, only the start date is downloaded'))

g = parser.add_argument_group('optional arguments')
g.add_argument('--ares', choices=['62','126','190','382','574','1148'], default='62', help=(
    "desired spectral resolution to convert to"))
g.add_argument('--src', help=(
    "Source directory of original CFSR data. By default $CFSR_DIR/T126 will be used"))
g.add_argument('--dst', help=(
    "Destination of the new resolution CFSR data. By default $CFSR_DIR/T<ares> will be used"))
g.add_argument('--daily', default=False, action="store_true", help=(
    "Only process the 00Z times"))

args=parser.parse_args()
if not args.end:
    args.end = args.start
if not args.src:
    args.src = os.getenv('CFSR_DIR')+'/T126'
if not args.dst:
    args.dst = os.getenv('CFSR_DIR')+'/T'+args.ares
args.src=os.path.abspath(args.src)
args.dst=os.path.abspath(args.dst)
print args



## deterimine the resolutions
xy = {
    '62' : ('192','94'),
    '126' : ('384','190'),
    '190' : ('576','288'),
    '382' : ('1152','576'),
    '574' : ('1760','880'),
    '1148': ('2304','1152'),
}
vres = '64'


## create the temporary directory
tmpdir = os.getenv('TMP_DIR_LOCAL')+'/chgres_cfsr'
if os.path.exists(tmpdir):
    shutil.rmtree(tmpdir)
os.makedirs(tmpdir)


## process all the dates
cdate = dt.datetime.strptime(args.start,'%Y%m%d%H')
edate = dt.datetime.strptime(args.end, '%Y%m%d%H')
while cdate <= edate:
    print cdate
    filepfx=cdate.strftime('/%Y/%Y%m/%Y%m%d/%Y%m%d%H')

    ## make sure the output directory exists
    outdir=os.path.dirname(args.dst+filepfx)
    if not os.path.exists(outdir):
        os.makedirs(outdir)

    ## setup the environment for the chgres script
    env = os.environ.copy()
    env2 = {
        'JCAP'    : args.ares,
        'LEVS'    : vres,
        'LONB'    : xy[args.ares][0],
        'LONR'    : xy[args.ares][0],    
        'LATB'    : xy[args.ares][1],
        'LATR'    : xy[args.ares][1],    
        
        'SIGINP'  : args.src+filepfx+'.sig',
        'SFCINP'  : args.src+filepfx+'.sfc',
        'SIGOUT'  : args.dst+filepfx+'.sig',
        'SFCOUT'  : args.dst+filepfx+'.sfc',
        
        'IDVC'    : '2',
        'IDSL'    : '1',
        'LSOIL'   : '4',
        #    'IVSSFC'  : '198410',
        'OUTTYPE' : '2',
        'IDRT'    : '4',
        
        'CLIMO_FIELDS_OPT':'3',
        'LANDICE_OPT' : '2',
        'CHGRESVARS' : 'NVCOORD=2',
        
        'EXECGLOBAL' : rootDir+'/cfs/bin',
        'FIXGLOBAL'  : os.getenv('FIX_DIR_AM'),
        'SIGLEVEL'   : os.getenv('FIX_DIR_AM')+'/global_hyblev.l{0}.txt'.format(vres),
        'OROGRAPHY'  : os.getenv('FIX_DIR_AM')+'/global_orography.t{0}.grb'.format(args.ares),
    }
    env.update(env2)

    sp.call(chgres_bin, env=env, shell=True,cwd=tmpdir)

    if args.daily:
        cdate += dt.timedelta(days=1)
    else:
        cdate += dt.timedelta(hours=6)

shutil.rmtree(tmpdir)
