#!/usr/bin/env bash

################################################################################
## run_cycle.sh
## Runs a single x hour forecast for the CFS model.
##
## Input arguments:
##  $1   input directory containing the initial conditions of the forecast
##  $2   output directory to place results
##  $3   start date, in YYYYMMDDHH format
##  $4   forecast lenght, in hours, normally is 6 or 9 hours
##  $5   period, in hours, of atmospheric output (ocean, for now, only saves
##       output at 6 hours)
##  $6   atmospheric resolution
##  $7   temporary work directory
##
## Environment variables  required:
##   NPROC_AM  number of cores to use for the GFS
##   NPROC_OM  number of cores to use for the MOM
##             + one additional implicit core for the coupler
################################################################################
set -e

echo "CFSv2 LETKF"
echo "arguments: $@"
echo "main host: $(hostname)"


## Experiment setup
## ------------------------------

SRC_DIR=$1
OUT_DIR=$2
START_DATE=$3
FCST_LEN=$4               # forecast length in hours
OUT_PERIOD=$5             # output file period (hours)
AM_RES=$6
WORKDIR=$7



#AM_RES=126         # atmosphere T resolution [62, ...]
#AM_RES_X=384
#AM_RES_Y=190

#AM_RES=62
if [ "$AM_RES" -eq "62" ]; then
    AM_RES_X=192
    AM_RES_Y=94
elif [ "$AM_RES" -eq "126" ]; then
    AM_RES_X=384
    AM_RES_Y=190
elif [ "$AM_RES" -eq "382" ]; then
    AM_RES_X=1152
    AM_RES_Y=576
else
    echo "unsupported atm resolution: $AM_RES"	 
fi	 

OM_RES=05         # ocean resolution [05 or 1x1]

CPL_PERIOD=300    # coulping period (s)


## Computer configuration
## ------------------------------
#WORKDIR=/dev/shm/$USER/CFS
#WORKDIR=/lustre/tsluka/tmp/$MEM

echo "WORKDIR  = $WORKDIR"
echo $NPROC_OM
echo $NPROC_AM

#x###############################################################################
# shouldn't have to modify below here
################################################################################


# create the working directory
rm -rf $WORKDIR
mkdir -p $WORKDIR
cd $WORKDIR

#copy the main executables over
echo "Copying executables..."
cp $CFS_LETKF_ROOT/cfs/bin/* .  &

# create coupled namelist
echo "creating coupled namelist (cpl_nml)..."
source $CFS_LETKF_ROOT/run/config_files/cpl_nml > cpl_nml

cl="ln -s"  ## either copy or link files, #TODO depending on where our tmp folder is

# Ocean Init
########################################
mkdir RESTART
mkdir IRESTART

# create config files
echo "Creating MOM config files..."
source $CFS_LETKF_ROOT/run/config_files/input.nml > input.nml
$cl $CFS_LETKF_ROOT/run/config_files/diag_table . &
$cl $CFS_LETKF_ROOT/run/config_files/data_table . &

# copy fix files, select the correct ones
# based on the desired resolution
echo "Copying MOM fix files..."
$cl $FIX_DIR_OM/MOM4LND${OM_RES}GFSOCNt${AM_RES}.msk MOM4LND_GFSOCN &
$cl $FIX_DIR_OM/fluxes_init_OM_t${AM_RES} fluxes_init_OM &
mkdir INPUT
cd INPUT
$cl $FIX_DIR_OM/grid_spec_$OM_RES.nc.T$AM_RES grid_spec.nc &
$cl $FIX_DIR_OM/chl_$OM_RES.nc chl.nc &
$cl $FIX_DIR_OM/r2ts_clim.nc . &
$cl $FIX_DIR_OM/sst_ice_clim.nc . &
$cl $FIX_DIR_OM/runoff_$OM_RES.nc runoff.nc &
$cl $FIX_DIR_OM/ohf_sice.nc . &
cd ..

# copy initial conditions
echo "Copying MOM initial conditions..."
cd INPUT
$cl $SRC_DIR/$START_DATE.ice_model.res.nc                ice_model.res.nc &
$cl $SRC_DIR/$START_DATE.ocean_density.res.nc            ocean_density.res.nc             ## really needed??
$cl $SRC_DIR/$START_DATE.ocean_sbc.res.nc                ocean_sbc.res.nc                 ## really needed??
$cl $SRC_DIR/$START_DATE.ocean_velocity.res.nc           ocean_velocity.res.nc &
$cl $SRC_DIR/$START_DATE.ocean_velocity_advection.res.nc ocean_velocity_advection.res.nc &
$cl $SRC_DIR/$START_DATE.ocean_freesurf.res.nc           ocean_freesurf.res.nc &
$cl $SRC_DIR/$START_DATE.ocean_temp_salt.res.nc          ocean_temp_salt.res.nc &
$cl $SRC_DIR/$START_DATE.ocean_frazil.res.nc             ocean_frazil.res.nc &
$cl $SRC_DIR/$START_DATE.ocean_neutral.res.nc            ocean_neutral.res.nc &

cd ..


# Atmosphere init
########################################
# copy initial conditions
echo "Copying GFS initial conditions..."
$cl $SRC_DIR/$START_DATE.sfc sfc_ini &
$cl $SRC_DIR/$START_DATE.sig sig_ini &


# create namelists
echo "Creating GFS config files..."
source $CFS_LETKF_ROOT/run/config_files/gfs_namelist > gfs_namelist
source $CFS_LETKF_ROOT/run/config_files/gfs_namelist.rc > gfs_namelist.rc

# copy fix files
echo "Copying GFS fix files..."
$cl $FIX_DIR_AM/global_climaeropac_global.txt aerosol.dat &
$cl $FIX_DIR_AM/global_co2con.l64.f77 fort.15 &
$cl $FIX_DIR_AM/global_mtnvar.t$AM_RES.f77 fort.24 &
$cl $FIX_DIR_AM/global_tbthe.f77 fort.27 &
$cl $FIX_DIR_AM/global_o3prdlos.f77 fort.28 &
$cl $FIX_DIR_AM/global_cldtune.f77 fort.43 &
$cl $FIX_DIR_AM/global_o3clim.txt fort.48 &
$cl $FIX_DIR_AM/global_orography.t$AM_RES.grb orography &
$cl $FIX_DIR_AM/global_orography_uf.t$AM_RES.$AM_RES_X.$AM_RES_Y.grb orography_uf &
$cl $FIX_DIR_AM/global_sfc_emissivity_idx.txt sfc_emissivity_idx.txt &
$cl $FIX_DIR_AM/global_co2historicaldata_2009.txt co2historicaldata_2009.txt &
$cl $FIX_DIR_AM/global_solarconstantdata.txt solarconstantdata.txt &
mkdir fix_am
cd fix_am
$cl $FIX_DIR_AM/global_glacier.2x2.grb . &
$cl $FIX_DIR_AM/global_maxice.2x2.grb . &
$cl $FIX_DIR_AM/cfs_oi2sst1x1monclim19822001.grb . &
$cl $FIX_DIR_AM/global_snoclim.1.875.grb . &
$cl $FIX_DIR_AM/global_zorclim.1x1.grb . &
$cl $FIX_DIR_AM/global_albedo4.1x1.grb . &
$cl $FIX_DIR_AM/cfs_ice1x1monclim19822001.grb . &
$cl $FIX_DIR_AM/global_tg3clim.2.6x1.5.grb . &
$cl $FIX_DIR_AM/global_vegfrac.0.144.decpercent.grb . &
$cl $FIX_DIR_AM/global_vegtype.1x1.grb . &
$cl $FIX_DIR_AM/global_soiltype.1x1.grb . &
$cl $FIX_DIR_AM/global_soilmcpc.1x1.grb . &
$cl $FIX_DIR_AM/seaice_newland.grb . &
$cl $FIX_DIR_AM/global_shdmin.0.144x0.144.grb . &
$cl $FIX_DIR_AM/global_shdmax.0.144x0.144.grb . &
$cl $FIX_DIR_AM/global_slope.1x1.grb . &
$cl $FIX_DIR_AM/global_snoalb.1x1.grb . &
cd ..

wait

## Run the CFS model
########################################
echo "Running the CFS model..."
export OMP_NUM_THREADS=1
time mpirun -n 1 cfs_mlc_coupler : -n $NPROC_OM cfs_ocean_mom4ice : -n $NPROC_AM global_fcst
echo "Done running model...."

START_DATE=$(date -u -d"${START_DATE:0:8} ${START_DATE:8:10}")
mkdir -p $OUT_DIR

## move the GFS output
echo "Moving GFS output..."
cdate=$(date -u -d "$START_DATE" +%Y%m%d%H)
fdate=$(date -u -d "$START_DATE + 6 hours" +%Y%m%d%H)

for i in $(seq -f "%02g" $OUT_PERIOD $OUT_PERIOD $FCST_LEN); do    
    mv SIG.F$i $OUT_DIR/${cdate}_F$i.sig
    mv SFC.F$i $OUT_DIR/${cdate}_F$i.sfc
done


## move the MOM output
echo "Moving MOM output..."
mv IRESTART/${fdate}ocean_velocity.res.nc           $OUT_DIR/${cdate}_F06.ocean_velocity.res.nc &
mv IRESTART/${fdate}ocean_velocity_advection.res.nc $OUT_DIR/${cdate}_F06.ocean_velocity_advection.res.nc &
mv IRESTART/${fdate}ocean_freesurf.res.nc           $OUT_DIR/${cdate}_F06.ocean_freesurf.res.nc &
mv IRESTART/${fdate}ocean_temp_salt.res.nc          $OUT_DIR/${cdate}_F06.ocean_temp_salt.res.nc &
mv IRESTART/${fdate}ocean_frazil.res.nc             $OUT_DIR/${cdate}_F06.ocean_frazil.res.nc &
mv IRESTART/${fdate}ocean_neutral.res.nc            $OUT_DIR/${cdate}_F06.ocean_neutral.res.nc &
mv IRESTART/${fdate}ice_model.res.nc                $OUT_DIR/${cdate}_F06.ice_model.res.nc &

#are the following really needed?
mv IRESTART/${fdate}ocean_density.res.nc            $OUT_DIR/${cdate}_F06.ocean_density.res.nc &
mv IRESTART/${fdate}ocean_sbc.res.nc                $OUT_DIR/${cdate}_F06.ocean_sbc.res.nc &

wait

echo "Done."
