#!/usr/bin/env python
############################################################
##
## TODO, insert description
##
############################################################

## load buil-in python modules
import argparse
import os, shutil, sys
import subprocess as sp
from glob import glob
import datetime as dt
import hashlib

## load our own modules
import common

## setup the logging system
log = common.setupLog()

## determine which parts of the script to run, mainly for debugging,
## For normal operations these should all be True
do_cfs      = True
do_atmcnvt  = True
do_ocnobsop = True
do_cleanup  = True


############################################################
## get the command line / env arguments

parser = argparse.ArgumentParser(description=(
    "TODO, insert descriptio"))

## required variables
parser.add_argument('path', metavar="PATH", help=(
    "Path to the directory storing the experiment."))
parser.add_argument('date', metavar="DATE", help=(
    "Date to start a forecast from, in YYYYMMDDHH format"))
parser.add_argument('ensNum', metavar="ENS_NUM", type=int, help=(
    "ensemble member number"))

parser.add_argument("--ares", type=int, help=(""))
parser.add_argument("--oobs", help=(
   "Directory containing the ocean observations to be assimilated. If argument is not present, "
   "it is assumed no ocean observations are to be used."))

parser.add_argument("--3d", action="store_true", dest="is3d")

## parse the arguments
args = parser.parse_args()
args.date = dt.datetime.strptime(args.date, "%Y%m%d%H")
args.path = os.path.abspath(args.path)
args.fixDir = os.path.abspath(os.getenv("FIX_DIR_OM"))
args.letkfDir = os.path.abspath(os.getenv("CFS_LETKF_ROOT") + '/letkf-mom')
args.ores = '05'
args.ares_x,args.ares_y = common.getAtmRes(args.ares)
args.wrkdir = os.path.abspath(os.getenv("TMP_DIR_SHARED")+"/cfs_fcst_" + \
                              hashlib.md5(args.path).hexdigest()[0:6] + \
                              "_{:03d}".format(args.ensNum))
assert( args.ensNum > 0 and args.ensNum <= common.getEnsMem(args.path))

## date: the date the forecast was initialized from
dateShort = args.date.strftime("%Y%m%d%H")
dateDir   = args.date.strftime("/%Y/%Y%m/%Y%m%d/%Y%m%d%H/")
## ndate: the next date, the date of the analysis
ndate      = args.date + dt.timedelta(hours=6)
ndateShort  = ndate.strftime("%Y%m%d%H")
ndateDir    = ndate.strftime("/%Y/%Y%m/%Y%m%d/%Y%m%d%H/")


############################################################
## print some basic information
log.info("CFSv2-LETKF ensemble member step.")
log.info("Runs the forecast and any other required per member pre LETKF steps")
log.info("Travis Sluka, University of Maryland, 2016")
log.info("")
log.info("Configuration:\n"+str(args)+"\n")

if args.oobs is None:
   log.warn("No ocean observations directory is specified, not ocean obs will be assimilated")
   
## make sure the wrk directory is empty
if os.path.exists(args.wrkdir):
   shutil.rmtree(args.wrkdir)
   os.makedirs(args.wrkdir)
   
############################################################
## run the CFS forecast
if do_cfs:
   log.info("Running the CFS forecast...")
   cmd = 'run_fcst {0}/anal/{1:03d} {0}/gues/{1:03d} {2} --wrkdir {3}'.format(
      args.path, args.ensNum, dateShort, args.wrkdir)
   if args.is3d: cmd += " --len 6 --period 6"
   if (sp.call(cmd, shell=True) > 0):
      log.error("Problem running CFS forecast.")
      sys.exit(1)

      
############################################################
## convert atmosphere spectral files to gridded
if do_atmcnvt:
   log.info("Converting atmosphere spectral files to gridded...")
   jobs = []
   
   if args.is3d:
      fcstHrStart = 6
      fcstHrEnd = 6
      baseSlot = 1
   else:
      fcstHrStart = 3
      fcstHrEnd   = 9
      baseSlot    = 4 ## hour 6
      
   for hr in range(fcstHrStart, fcstHrEnd+1):
      tmpDir = args.wrkdir+'/ss2grd_wrk_{0:02d}'.format(hr)
      if (not os.path.exists(tmpDir)): os.makedirs(tmpDir)
      os.symlink("{}/gues/{:03d}/{}_F{:02d}.sig".format(args.path,args.ensNum,dateShort,hr), tmpDir+'/fort.11')
      os.symlink("{}/gues/{:03d}/{}_F{:02d}.sfc".format(args.path,args.ensNum,dateShort,hr), tmpDir+'/fort.12')
      with open(tmpDir+'/ssio.nml', 'w') as f:
         f.write('$common_gfs nlon={} nlat={} gfs_jcap={} nlev=64 /'.format(
            args.ares_x, args.ares_y, args.ares))
      cmd =('$CFS_LETKF_ROOT/util/bin/ss2grd; '
            'cp fort.31 {}/gues/{:03d}/{}_F{:02d}.grd'.format(
               args.path,args.ensNum, dateShort, hr))
      jobs.append(sp.Popen(cmd, shell=True, cwd=tmpDir))
   for j in jobs:
      j.wait()
      if (j.returncode != 0 ):
         log.error("Problem converting spectral to gridded")
         sys.exit(1)

############################################################
## run ocean observation operator
if do_ocnobsop and args.oobs is not None:
   log.info("Running OCN observation operator...")   
   ## get the required files ready
   obsFile = args.oobs + ndate.strftime('/%Y/%Y%m/%Y%m%d/%Y%m%d%H.dat')
   log.info("Using obs file: "+obsFile)
   tmpDir = args.wrkdir+'/ocnObsop'
   if (not os.path.exists(tmpDir)): os.makedirs(tmpDir)
   os.symlink(args.letkfDir +'/obs/obsop', tmpDir+'/obsop')
   os.symlink(args.fixDir+'/grid_spec_{}.nc.T{}'.format(args.ores,args.ares),
              tmpDir+'/grid_spec.nc')
   shutil.copy(args.path+"/letkf.nml", tmpDir+"/input.nml")
   for f in glob("{}/gues/{:03d}/{}_F06.ocean_*.res.nc".format(
         args.path, args.ensNum, dateShort)):
      f2 = os.path.basename(f)
      os.symlink(f, tmpDir+'/gs01.'+f2[15:])
   shutil.copy(obsFile, tmpDir+'/obsin.dat')

   ## Run the observation operator
   ret = sp.call('obsop -obsin obsin.dat -gues gs01 -obsout {}_ocn{:03d}.dat'.format(
      args.path+'/obsop/'+ndate.strftime('%Y%m%d%H'), args.ensNum),
           shell=True, cwd=tmpDir)
   if ret != 0:
      log.critical('error running ocean observation operator')
      sys.exit(1)


############################################################
## copy logs/file and cleanup
if do_cleanup:
   log.info("Cleaning up and copying files...")
   shutil.rmtree(args.wrkdir)

